# Generated by Django 5.1.3 on 2024-11-11 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acteur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editeur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Importance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manga', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mangaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangaka', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PEGI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pegi', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Poids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Resus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resus', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Taille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Musique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('album', models.CharField(blank=True, max_length=100, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='musique/')),
                ('annee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.annee')),
            ],
        ),
        migrations.CreateModel(
            name='LiaisonManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.annee')),
                ('editeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.editeur')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.manga')),
                ('mangaka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mangaka')),
                ('musique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.musique')),
                ('pegi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pegi')),
            ],
        ),
        migrations.CreateModel(
            name='Perso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('surnom', models.CharField(blank=True, max_length=50, null=True)),
                ('anniversaire', models.DateField(blank=True, null=True)),
                ('acteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.acteur')),
                ('couleur_cheveux', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheveux', to='api.couleur')),
                ('couleur_yeux', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yeux', to='api.couleur')),
                ('importance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.importance')),
                ('manga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.manga')),
                ('poids', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.poids')),
                ('resus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.resus')),
                ('taille', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.taille')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.type')),
            ],
        ),
        migrations.CreateModel(
            name='LiaisonPerso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.acteur')),
                ('cheveux', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liaison_cheveux', to='api.couleur')),
                ('importance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.importance')),
                ('yeux', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liaison_yeux', to='api.couleur')),
                ('manga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.manga')),
                ('perso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perso')),
                ('poids', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.poids')),
                ('resus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.resus')),
                ('taille', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.taille')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.type')),
            ],
        ),
    ]
